### ISSUE TITLE
Role fails with "AnsibleUndefinedVariable: 'dict object' has no attribute 'iteritems'"

### ISSUE THREAD

**Issue by hpio** [ahuffman/ansible-sudoers#16]
Ansible fails with the following error (thats using only one entry in sudoer_specs)
```
  vars:
    - sudoer_specs:
        - name: vagrant
          users: vagrant
          comment: Stuff for admins
          hosts: ALL
          operators: ALL
          tags:
            - NOPASSWD
          commands: ALL
```


`TASK [../../ansible-sudoers : Ensure the sudoers file is valid and up to date (separate specs)] ***
fatal: [centos7]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'iteritems'"}`

`
ansible --version                                                                                                                                                                                                                             
ansible 2.3.1.0
  config file =
  configured module search path = Default w/o overrides
  python version = 3.5.2 (default, Oct 11 2016, 05:05:28) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)]`
