### ISSUE TITLE
explicit 'become: False' in task 'Ensure local backup directory exists'

### ISSUE THREAD

**Issue by soloradish** [ahuffman/ansible-sudoers#39]
https://github.com/ahuffman/ansible-sudoers/blob/3920507e43b3ecfa910f031de71804db7bbae666/tasks/main.yml#L51

If I include this role in other playbooks, and set 'become: True' in playbook vars. This task will fail because my local machine require sudo password.

I think better to explicit add 'become: False' to this task.

**Comment by pjattke** [comment]
I also faced the same issue – I think local sudo privileges are not needed anyway. I would be happy to see this change integrated into master. Would that be possible @ahuffman?

**Comment by ahuffman** [comment]
1. Would changing the default `sudoers_backup_path` to `~/sudoers_backups` resolve the issue if we set `become: False` on this task?  I believe we have the become in there because the backup path is relative to the local ansible control node playbook directory, and would require privilege to write there if running as a non-root user.  

2. Another solution we could add is a `sudoer_backup_become` var and you can configure as you wish.

Let me know what makes more sense, but I think I'm probably leaning towards option 2.

**Comment by ahuffman** [comment]
@soloradish @pjattke can you test out https://github.com/ahuffman/ansible-sudoers/tree/sudoers_backup_become and let me know if this works for you?

**Comment by pjattke** [comment]
@ahuffman Thanks for looking into that! The solution that I have applied so far is simply setting `become: False` in the respective task that keeps failing (of course, on a local copy of your role):

```
 - name: "Ensure local backup directory exists"
   file:
     state: "directory"
     path: "{{ sudoers_backup_path }}"
     mode: "0755"
   delegate_to: "localhost"
   connection: "local"
+  become: False                    <<< added line
   when:
     - "sudoers_backup | bool"
     - "sudoers_backup_path != ''"
```

However, I can see that this makes things less flexible and thus I think that your proposed solution 2) would be better suited. I have tested the `sudoers_backup_become` branch. However, I get the following error message even though I have defined `sudoer_backup_become: False`:

```
fatal: [hostA]: FAILED! => {
    "msg": "failed to transfer file to /etc/sudoers /Users/patrick/git/<redacted>/ansible/backups/host123/sudoers-backups/host123/etc/sudoers:
             dd: failed to open '/etc/sudoers': Permission denied"
}
```
I think this is because you also use this variable to define `become` in the task named [_Backup sudoers file_](https://github.com/ahuffman/ansible-sudoers/blob/d15f19b80cc484866ed2cdb324c5d44545fca31d/tasks/main.yml#L69). On the remote, however, sudo permissions are always required to allow reading the sudoers file. Therefore, I think that the change in this line should be reverted.

I would be happy to test again after you made this change. Thanks a lot!
